### ISSUE TITLE
Java generation from lex files is missing in the build process

### ISSUE THREAD

**Issue by dupuisa** [dupuisa/i-CodeCNES#3]

**Comment by dupuisa** [comment]
Following projects contain lex files which should be used to generate java files through ant task defined in the build.xml file : fr.cnes.*.metrics and fr.cnes.*.rules

**Comment by dupuisa** [comment]
The generated files should be placred into a specific directory.

**Comment by opcoach** [comment]
This has been done in commit 3803a73fd1b78685876a3d05b3e6291776fc17af
