### ISSUE TITLE
Export crash

### ISSUE THREAD

**Issue by dupuisa** [dupuisa/i-CodeCNES#58]
XML export is craching (nullpointerException)
Map "parameters" in CheckerFileCreationExportWizardPage is not initialized and not set with user values in ExportXml.

**Comment by opcoach** [comment]
In CheckerFileCreationExportWizardPage the Export service is used. This service searches for the right exporter to use depending on the file extension of the result file. 
It seems that the  XML exporter needs additional parameters that are not set, and anyway, the values entered in the wizard are not set on the final IExport instance.

**Comment by WaldoFR** [comment]
Problem came from `CheckerExport WizardPage` initial content setting, default values of parameters weren't updated to `CheckerFileCreationExport WizardPage` when retrieving them using export service.
