### ISSUE TITLE
Travis-CI do not run test on build

### ISSUE THREAD

**Issue by WaldoFR** [dupuisa/i-CodeCNES#71]
Once a build is done, Travis-ci run the command `mvn test -B`, however tests always return true even when if we volontary introduce failures in it.

- [x] Travis-CI should indicate the build as **errored** if a test fails or if there is an error during test execution.

**Comment by WaldoFR** [comment]
Travis-CI build (`.travis.yml`) was modified to : 
* Not execute anymore the default build;
* Run the install command including test;
* Be executed in a Docker container ( `sudo: false` ).

This solution was tested localy to verify that test executed during the `mvn install` notify failures. Also, commit aadc110 show that test failure also informs Travis itself causing build to be errored.

However, local test with command `mvn test` still return true even in case of failure, false-positive was not solved ( @opcoach ).

Regards,
Omar

**Comment by opcoach** [comment]
More information here : 
https://stackoverflow.com/questions/28721925/is-it-possible-to-configure-tycho-surefire-to-run-in-the-test-phase

Actually, the tests are included in the plugin fragments and seems to be called in the integration-test phase and not the test phase as expected by travis. 

May be a configuration on the travis side would be more appropriate to say : test phase is actually the integration-test phase in my pom.

**Comment by WaldoFR** [comment]
Thank you for your answer @opcoach, that's mean that the command `mvn verify` is the one that should be used to execute i-Code tests instead of `mvn test`. I'll modify Travis-CI execution to specify it.

Regards,
Omar
