### ISSUE TITLE
Command line crash on low memory computers

### ISSUE THREAD

**Issue by WaldoFR** [dupuisa/i-CodeCNES#72]
It seems that i-Code command line crash on analysis even when running it on only one file when launched from a computer with 1Go of RAM.

A possible line of approach would be to define JVM max heap size argument at launching for icode.product, with the argument -Xmx256M for instance.

**Comment by opcoach** [comment]
In case we can change the launching VM parameter in 'launching' tab of icode.product file to -Xmx512M

**Comment by WaldoFR** [comment]
Hello @opcoach ,

Thank you for your answer.

Changes made in commit 9ba73bb improved the analysis performance making it consuming less memory but also avoid the analyzer to use more than 90% of the max memory allocated in the JVM.

Wouldn't -Xmx512M argument prevent low memory computers to run the application ? (And at the same time decrease performance of huge memory computers?).

Is there another solution to be able to scale JVM max memory pending free memory available when launching the application instead of setting it before building the product ?

Regards,
Omar
