### ISSUE TITLE
Limitation : Running icode command line with Powershell on Windows won't execute analysis

### ISSUE THREAD

**Issue by WaldoFR** [dupuisa/i-CodeCNES#73]
Using `PowerShell`, I can execute only `eclipsec.exe` (impossible to run `icode.exe`).

Executing `eclipsec.exe`  returns the help usage of the command line, but it won't launch analysis on files using this command :  
`.\eclipsec.exe .\myfile.sh`

**Comment by opcoach** [comment]
Dans fr.cnes.icode.repository/target/products/icode.product/win32/win32/x86/icode il y a la commande icode.exe.. c'est elle qu'il faut executer...

**Comment by WaldoFR** [comment]
I get no feedback from **icode.exe** when running it with Windows 7. Maybe it's a `Powershell` issue, I'll try with cmd.exe tomorrow.

**Comment by WaldoFR** [comment]
It seems that the problem came from `PowerShell`, I can not understand why : 
![image](https://user-images.githubusercontent.com/10857454/28946223-0d402360-78aa-11e7-911f-824507b464eb.png)
![image](https://user-images.githubusercontent.com/10857454/28946205-f593f250-78a9-11e7-86ba-5eed043422ef.png)

However, only `eclipsec.exe` gives feedback in the console, the command line do not show help with `icode.exe` executable : 
![image](https://user-images.githubusercontent.com/10857454/28946490-4f20540c-78ab-11e7-9099-198b0abcffcb.png)

**Comment by WaldoFR** [comment]
This issue was edited to keep a trace of this **Limitation** when using `Powershell` on `Windows`.

Two more issues were created from this one : 
* #80 on `icode.exe` not displaying output in the console;
* #79  on `ecilpsec.exe` file that should be removed from the build.

**Comment by WaldoFR** [comment]
Reported in User's manual.
