### ISSUE TITLE
Build create an useless eclipsec.exe file.

### ISSUE THREAD

**Issue by WaldoFR** [dupuisa/i-CodeCNES#79]
The file `eclipsec.exe` should be removed from the build.

**Comment by opcoach** [comment]
TO fix this bug, you must add a file named 'p2.inf' besides the .product files (in the fr.cnes.icode.repository project).  This file contains an instruction to remove the file after the build, and is managed by tycho. 

I created a pull request to fix and add this file in the product. I tested it locally, it works well. 

The content of the file is : 

instructions.configure=org.eclipse.equinox.p2.touchpoint.natives.remove(path:${installFolder}/eclipsec.exe);
