### ISSUE TITLE
Command line should display an output on console.

### ISSUE THREAD

**Issue by WaldoFR** [dupuisa/i-CodeCNES#80]
Command line `icode.exe` launched with `cmd.exe` of `Windows` do not display information in the console, even when we try to reach help.

![image](https://user-images.githubusercontent.com/10857454/28946490-4f20540c-78ab-11e7-9099-198b0abcffcb.png)

**Comment by opcoach** [comment]
The parameter '-consoleLog' is missing in the icode.product file. 

You must add it in the Launching tab of icode.product file (see also icodeIDE.product, in the launching tab it is the present)
